WITH ORDERS_BASE AS (
SELECT SELLER_ID,
CATEGORY,
DATE_TRUNC('month', CREATED_AT) AS MONTH,
ROUND(SUM(REVENUE), 2) AS MONTHLY_REVENUE
FROM ORDERS
WHERE STATUS = 'completed'
AND EXTRACT(YEAR FROM CREATED_AT) = EXTRACT(YEAR FROM CURRENT_DATE)
GROUP BY SELLER_ID, CATEGORY, DATE_TRUNC('month', CREATED_AT)
),
AGG_RANKED AS (
SELECT SELLER_ID,
CATEGORY,
MONTH,
MONTHLY_REVENUE,
DENSE_RANK() OVER(PARTITION BY CATEGORY, MONTH ORDER BY MONTHLY_REVENUE DESC) AS CATEGORY_RANK
FROM ORDERS_BASE
), 
PREV_MONTH_INCLUSIVE AS (
SELECT SELLER_ID,
CATEGORY,
MONTH,
MONTHLY_REVENUE,
CATEGORY_RANK,
LAG(CATEGORY_RANK) OVER(PARTITION BY SELLER_ID, CATEGORY ORDER BY MONTH) AS PREV_MONTH_RANK
FROM AGG_RANKED
)
SELECT A.SELLER_ID,
SEL.NAME AS SELLER_NAME,
S.CATEGORY,
S.MONTH,
S.MONTHLY_REVENUE,
S.CATEGORY_RANK,
S.PREV_MONTH_RANK,
S.PREV_MONTH_RANK - S.CATEGORY_RANK AS RANK_CHANGE,
ROUND(SUM(S.MONTHLY_REVENUE) OVER(PARTITION BY S.SELLER_ID, S.CATEGORY ORDER BY MONTH), 2) AS CUMULATIVE_REVENUE
FROM PREV_MONTH_INCLUSIVE S
JOIN SELLERS SEL
ON SEL.SELLER_ID = S.SELLER_ID
ORDER BY CATEGORY, MONTH, CATEGORY_RANK;



-- Get Top 3 sellers for at least 3 consecutive months :
-- Consider the output of the above query as a aggregated_ranked_table 
WITH TOP_SELLERS AS (
SELECT 
    SELLER_ID,
    SELLER_NAME,
    CATEGORY,
    MONTH,
    CATEGORY_RANK,
    LAG(CATEGORY_RANK, 1) OVER(PARTITION BY SELLER_ID, CATEGORY ORDER BY MONTH) AS PREV_MONTH_RANK,
    LAG(CATEGORY_RANK, 2) OVER(PARTITION BY SELLER_ID, CATEGORY ORDER BY MONTH) AS SECOND_PREV_MONTH_RANK
FROM AGGREGATED_RANKED_TABLE
)
SELECT 
    SELLER_ID,
    SELLER_NAME,
    CATEGORY
FROM TOP_SELLERS
WHERE CATEGORY_RANK <= 3
AND PREV_MONTH_RANK <= 3
AND SECOND_PREV_MONTH_RANK <= 3
AND PREV_MONTH_RANK IS NOT NULL   -- ensures 3 months of data exist
AND SECOND_PREV_MONTH_RANK IS NOT NULL;

-- Note : Pattern: compute window functions in a CTE, filter in the outer query. Never filter on a column alias defined in the same SELECT.

